export const linksHeader = [
    {
      label: 'Clienti',
      link: '/clienti',
      links: [
        {
          label: 'Ricerca Cliente',
          link: '/clienti/sotto-link-1',
        },
        {
          label: 'Inserimento Nuovo Cliente',
          link: '/clienti/sotto-link-2',
        },
      ],
    },
    {
      label: 'Portafoglio',
      link: '/portafoglio',
      links: [
        {
          label: 'Ricerca Polizza',
          link: '/clienti/sotto-link-1',
        },
      ],
    },
    {
      label: 'Contabilità',
      link: '/contabilità',
      links: [
        {
          label: 'Polizze in Scadenza',
          link: '/clienti/sotto-link-1',
        },
        {
          label: 'Rate in Scadenza',
          link: '/clienti/sotto-link-2',
        },
      ],
    },
  ];

  export const regioniItaliane = [
    { value: 'Abr', label: 'Abruzzo' },
    { value: 'Basi', label: 'Basilicata' },
    { value: 'Cal', label: 'Calabria' },
    { value: 'Cam', label: 'Campania' },
    { value: 'Emi', label: 'Emilia-Romagna' },
    { value: 'Fri', label: 'Friuli-Venezia Giulia' },
    { value: 'Laz', label: 'Lazio' },
    { value: 'Lig', label: 'Liguria' },
    { value: 'Lom', label: 'Lombardia' },
    { value: 'Mar', label: 'Marche' },
    { value: 'Mol', label: 'Molise' },
    { value: 'Pie', label: 'Piemonte' },
    { value: 'Pug', label: 'Puglia' },
    { value: 'Sar', label: 'Sardegna' },
    { value: 'Sic', label: 'Sicilia' },
    { value: 'Tos', label: 'Toscana' },
    { value: 'TAA', label: 'Trentino-Alto Adige' },
    { value: 'Umb', label: 'Umbria' },
    { value: 'Val', label: "Valle d'Aosta" },
    { value: 'Ven', label: 'Veneto' },
  ];


  export const nazioniDelMondo = [
    { value: 'AFG', label: 'Afghanistan' },
    { value: 'ALB', label: 'Albania' },
    { value: 'DZA', label: 'Algeria' },
    { value: 'AND', label: 'Andorra' },
    { value: 'AGO', label: 'Angola' },
    { value: 'ATG', label: 'Antigua e Barbuda' },
    { value: 'ARG', label: 'Argentina' },
    { value: 'ARM', label: 'Armenia' },
    { value: 'AUS', label: 'Australia' },
    { value: 'AUT', label: 'Austria' },
    { value: 'AZE', label: 'Azerbaigian' },
    { value: 'BHS', label: 'Bahamas' },
    { value: 'BHR', label: 'Bahrein' },
    { value: 'BGD', label: 'Bangladesh' },
    { value: 'BRB', label: 'Barbados' },
    { value: 'BLR', label: 'Bielorussia' },
    { value: 'BEL', label: 'Belgio' },
    { value: 'BLZ', label: 'Belize' },
    { value: 'BEN', label: 'Benin' },
    { value: 'BTN', label: 'Bhutan' },
    { value: 'BOL', label: 'Bolivia' },
    { value: 'BIH', label: 'Bosnia ed Erzegovina' },
    { value: 'BWA', label: 'Botswana' },
    { value: 'BRA', label: 'Brasile' },
    { value: 'BRN', label: 'Brunei' },
    { value: 'BGR', label: 'Bulgaria' },
    { value: 'BFA', label: 'Burkina Faso' },
    { value: 'BDI', label: 'Burundi' },
    { value: 'KHM', label: 'Cambogia' },
    { value: 'CMR', label: 'Camerun' },
    { value: 'CAN', label: 'Canada' },
    { value: 'CPV', label: 'Capo Verde' },
    { value: 'CAF', label: 'Repubblica Centrafricana' },
    { value: 'TCD', label: 'Ciad' },
    { value: 'CHL', label: 'Cile' },
    { value: 'CHN', label: 'Cina' },
    { value: 'COL', label: 'Colombia' },
    { value: 'COM', label: 'Comore' },
    { value: 'COG', label: 'Congo (Brazzaville)' },
    { value: 'COD', label: 'Congo (Kinshasa)' },
    { value: 'CRI', label: 'Costa Rica' },
    { value: 'CIV', label: "Costa d'Avorio" },
    { value: 'HRV', label: 'Croazia' },
    { value: 'CUB', label: 'Cuba' },
    { value: 'CYP', label: 'Cipro' },
    { value: 'CZE', label: 'Repubblica Ceca' },
    { value: 'DNK', label: 'Danimarca' },
    { value: 'DJI', label: 'Gibuti' },
    { value: 'DMA', label: 'Dominica' },
    { value: 'DOM', label: 'Repubblica Dominicana' },
    { value: 'ECU', label: 'Ecuador' },
    { value: 'EGY', label: 'Egitto' },
    { value: 'SLV', label: 'El Salvador' },
    { value: 'GNQ', label: 'Guinea Equatoriale' },
    { value: 'ERI', label: 'Eritrea' },
    { value: 'EST', label: 'Estonia' },
    { value: 'SWZ', label: 'Eswatini' },
    { value: 'ETH', label: 'Etiopia' },
    { value: 'FJI', label: 'Figi' },
    { value: 'FIN', label: 'Finlandia' },
    { value: 'FRA', label: 'Francia' },
    { value: 'GAB', label: 'Gabon' },
    { value: 'GMB', label: 'Gambia' },
    { value: 'GEO', label: 'Georgia' },
    { value: 'DEU', label: 'Germania' },
    { value: 'GHA', label: 'Ghana' },
    { value: 'GRC', label: 'Grecia' },
    { value: 'GRD', label: 'Grenada' },
    { value: 'GTM', label: 'Guatemala' },
    { value: 'GIN', label: 'Guinea' },
    { value: 'GNB', label: 'Guinea-Bissau' },
    { value: 'GUY', label: 'Guyana' },
    { value: 'HTI', label: 'Haiti' },
    { value: 'HND', label: 'Honduras' },
    { value: 'HUN', label: 'Ungheria' },
    { value: 'ISL', label: 'Islanda' },
    { value: 'IND', label: 'India' },
    { value: 'IDN', label: 'Indonesia' },
    { value: 'IRN', label: 'Iran' },
    { value: 'IRQ', label: 'Iraq' },
    { value: 'IRL', label: 'Irlanda' },
    { value: 'ISR', label: 'Israele' },
    { value: 'ITA', label: 'Italia' },
    { value: 'JAM', label: 'Giamaica' },
    { value: 'JPN', label: 'Giappone' },
    { value: 'JOR', label: 'Giordania' },
    { value: 'KAZ', label: 'Kazakistan' },
    { value: 'KEN', label: 'Kenya' },
    { value: 'KIR', label: 'Kiribati' },
    { value: 'KWT', label: 'Kuwait' },
    { value: 'KGZ', label: 'Kirghizistan' },
    { value: 'LAO', label: 'Laos' },
    { value: 'LVA', label: 'Lettonia' },
    { value: 'LBN', label: 'Libano' },
    { value: 'LSO', label: 'Lesotho' },
    { value: 'LBR', label: 'Liberia' },
    { value: 'LBY', label: 'Libia' },
    { value: 'LIE', label: 'Liechtenstein' },
    { value: 'LTU', label: 'Lituania' },
    { value: 'LUX', label: 'Lussemburgo' },
    { value: 'MDG', label: 'Madagascar' },
    { value: 'MWI', label: 'Malawi' },
    { value: 'MYS', label: 'Malesia' },
    { value: 'MDV', label: 'Maldive' },
    { value: 'MLI', label: 'Mali' },
    { value: 'MLT', label: 'Malta' },
    { value: 'MHL', label: 'Isole Marshall' },
    { value: 'MRT', label: 'Mauritania' },
    { value: 'MUS', label: 'Mauritius' },
    { value: 'MEX', label: 'Messico' },
    { value: 'FSM', label: 'Micronesia' },
    { value: 'MDA', label: 'Moldavia' },
    { value: 'MCO', label: 'Monaco' },
    { value: 'MNG', label: 'Mongolia' },
    { value: 'MNE', label: 'Montenegro' },
    { value: 'MAR', label: 'Marocco' },
    { value: 'MOZ', label: 'Mozambico' },
    { value: 'MMR', label: 'Myanmar' },
    { value: 'NAM', label: 'Namibia' },
    { value: 'NRU', label: 'Nauru' },
    { value: 'NPL', label: 'Nepal' },
    { value: 'NLD', label: 'Paesi Bassi' },
    { value: 'NZL', label: 'Nuova Zelanda' },
    { value: 'NIC', label: 'Nicaragua' },
    { value: 'NER', label: 'Niger' },
    { value: 'NGA', label: 'Nigeria' },
    { value: 'PRK', label: 'Corea del Nord' },
    { value: 'NOR', label: 'Norvegia' },
    { value: 'OMN', label: 'Oman' },
    { value: 'PAK', label: 'Pakistan' },
    { value: 'PLW', label: 'Palau' },
    { value: 'PAN', label: 'Panama' },
    { value: 'PNG', label: 'Papua Nuova Guinea' },
    { value: 'PRY', label: 'Paraguay' },
    { value: 'PER', label: 'Perù' },
    { value: 'PHL', label: 'Filippine' },
    { value: 'POL', label: 'Polonia' },
    { value: 'PRT', label: 'Portogallo' },
    { value: 'QAT', label: 'Qatar' },
    { value: 'KOR', label: 'Corea del Sud' },
    { value: 'MDA', label: 'Moldavia' },
    { value: 'ROU', label: 'Romania' },
    { value: 'RUS', label: 'Russia' },
    { value: 'RWA', label: 'Ruanda' },
    { value: 'KNA', label: 'Saint Kitts e Nevis' },
    { value: 'LCA', label: 'Santa Lucia' },
    { value: 'VCT', label: 'Saint Vincent e Grenadine' },
    { value: 'WSM', label: 'Samoa' },
    { value: 'SMR', label: 'San Marino' },
    { value: 'STP', label: 'Sao Tome e Principe' },
    { value: 'SAU', label: 'Arabia Saudita' },
    { value: 'SEN', label: 'Senegal' },
    { value: 'SRB', label: 'Serbia' },
    { value: 'SYC', label: 'Seychelles' },
    { value: 'SLE', label: 'Sierra Leone' },
    { value: 'SGP', label: 'Singapore' },
    { value: 'SVK', label: 'Slovacchia' },
    { value: 'SVN', label: 'Slovenia' },
    { value: 'SLB', label: 'Isole Salomone' },
    { value: 'SOM', label: 'Somalia' },
    { value: 'ZAF', label: 'Sudafrica' },
    { value: 'SSD', label: 'Sud Sudan' },
    { value: 'ESP', label: 'Spagna' },
    { value: 'LKA', label: 'Sri Lanka' },
    { value: 'SDN', label: 'Sudan' },
    { value: 'SUR', label: 'Suriname' },
    { value: 'SWE', label: 'Svezia' },
    { value: 'CHE', label: 'Svizzera' },
    { value: 'SYR', label: 'Siria' },
    { value: 'TWN', label: 'Taiwan' },
    { value: 'TJK', label: 'Tagikistan' },
    { value: 'TZA', label: 'Tanzania' },
    { value: 'THA', label: 'Tailandia' },
    { value: 'TLS', label: 'Timor Est' },
    { value: 'TGO', label: 'Togo' },
    { value: 'TON', label: 'Tonga' },
    { value: 'TTO', label: 'Trinidad e Tobago' },
    { value: 'TUN', label: 'Tunisia' },
    { value: 'TUR', label: 'Turchia' },
    { value: 'TKM', label: 'Turkmenistan' },
    { value: 'TUV', label: 'Tuvalu' },
    { value: 'UGA', label: 'Uganda' },
    { value: 'UKR', label: 'Ucraina' },
    { value: 'ARE', label: 'Emirati Arabi Uniti' },
    { value: 'GBR', label: 'Regno Unito' },
    { value: 'USA', label: 'Stati Uniti d\'America' },
    { value: 'URY', label: 'Uruguay' },
    { value: 'UZB', label: 'Uzbekistan' },
    { value: 'VUT', label: 'Vanuatu' },
    { value: 'VAT', label: 'Città del Vaticano' },
    { value: 'VEN', label: 'Venezuela' },
    { value: 'VNM', label: 'Vietnam' },
    { value: 'YEM', label: 'Yemen' },
    { value: 'ZMB', label: 'Zambia' },
    { value: 'ZWE', label: 'Zimbabwe' },
  ];

  export const provincePerRegione = [
    {Abr: ['Chieti', "L'Aquila", 'Pescara', 'Teramo']},
    {Basi: ['Matera', 'Potenza']},
    {Cal: ['Catanzaro', 'Cosenza', 'Crotone', 'Reggio Calabria', 'Vibo Valentia']},
    {Cam: ['Avellino', 'Benevento', 'Caserta', 'Napoli', 'Salerno']},
    {Emi: ['Bologna', 'Ferrara', 'Forlì-Cesena', 'Modena', 'Parma', 'Piacenza', 'Ravenna', 'Reggio Emilia', 'Rimini']},
    {Fri: ['Gorizia', 'Pordenone', 'Trieste', 'Udine']},
    {Laz: ['Frosinone', 'Latina', 'Rieti', 'Roma', 'Viterbo']},
    {Lig: ['Genova', 'Imperia', 'La Spezia', 'Savona']},
    {Lom: ['Bergamo', 'Brescia', 'Como', 'Cremona', 'Lecco', 'Lodi', 'Mantova', 'Milano', 'Monza e Brianza', 'Pavia', 'Sondrio', 'Varese']},
    {Mar: ['Ancona', 'Ascoli Piceno', 'Fermo', 'Macerata', 'Pesaro e Urbino']},
    {Mol: ['Campobasso', 'Isernia']},
    {Pie: ['Alessandria', 'Asti', 'Biella', 'Cuneo', 'Novara', 'Torino', 'Verbano-Cusio-Ossola', 'Vercelli']},
    {Pug: ['Bari', 'Barletta-Andria-Trani', 'Brindisi', 'Foggia', 'Lecce', 'Taranto']},
    {Sar: ['Cagliari', 'Carbonia-Iglesias', 'Medio Campidano', 'Nuoro', 'Ogliastra', 'Olbia-Tempio', 'Oristano', 'Sassari']},
    {Sic: ['Agrigento', 'Caltanissetta', 'Catania', 'Enna', 'Messina', 'Palermo', 'Ragusa', 'Siracusa', 'Trapani']},
    {Tos: ['Arezzo', 'Firenze', 'Grosseto', 'Livorno', 'Lucca', 'Massa-Carrara', 'Pisa', 'Pistoia', 'Prato', 'Siena']},
    {TAA: ['Bolzano', 'Trento']},
    {Umb: ['Perugia', 'Terni']},
    {Val: ["Valle d'Aosta"]},
    {Ven: ['Belluno', 'Padova', 'Rovigo', 'Treviso', 'Venezia', 'Verona', 'Vicenza']},
];

/* 
  export const provincePerRegione = [
    {regione: 'Abr', province: ['Chieti', "L'Aquila", 'Pescara', 'Teramo']},
    {regione: 'Basi', province: ['Matera', 'Potenza']},
    {regione: 'Cal', province: ['Catanzaro', 'Cosenza', 'Crotone', 'Reggio Calabria', 'Vibo Valentia']},
    {regione: 'Cam', province: ['Avellino', 'Benevento', 'Caserta', 'Napoli', 'Salerno']},
    {regione: 'Emi', province: ['Bologna', 'Ferrara', 'Forlì-Cesena', 'Modena', 'Parma', 'Piacenza', 'Ravenna', 'Reggio Emilia', 'Rimini']},
    {regione: 'Fri', province: ['Gorizia', 'Pordenone', 'Trieste', 'Udine']},
    {regione: 'Laz', province: ['Frosinone', 'Latina', 'Rieti', 'Roma', 'Viterbo']},
    {regione: 'Lig', province: ['Genova', 'Imperia', 'La Spezia', 'Savona']},
    {regione: 'Lom', province: ['Bergamo', 'Brescia', 'Como', 'Cremona', 'Lecco', 'Lodi', 'Mantova', 'Milano', 'Monza e Brianza', 'Pavia', 'Sondrio', 'Varese']},
    {regione: 'Mar', province: ['Ancona', 'Ascoli Piceno', 'Fermo', 'Macerata', 'Pesaro e Urbino']},
    {regione: 'Mol', province: ['Campobasso', 'Isernia']},
    {regione: 'Pie', province: ['Alessandria', 'Asti', 'Biella', 'Cuneo', 'Novara', 'Torino', 'Verbano-Cusio-Ossola', 'Vercelli']},
    {regione: 'Pug', province: ['Bari', 'Barletta-Andria-Trani', 'Brindisi', 'Foggia', 'Lecce', 'Taranto']},
    {regione: 'Sar', province: ['Cagliari', 'Carbonia-Iglesias', 'Medio Campidano', 'Nuoro', 'Ogliastra', 'Olbia-Tempio', 'Oristano', 'Sassari']},
    {regione: 'Sic', province: ['Agrigento', 'Caltanissetta', 'Catania', 'Enna', 'Messina', 'Palermo', 'Ragusa', 'Siracusa', 'Trapani']},
    {regione: 'Tos', province: ['Arezzo', 'Firenze', 'Grosseto', 'Livorno', 'Lucca', 'Massa-Carrara', 'Pisa', 'Pistoia', 'Prato', 'Siena']},
    {regione: 'TAA', province: ['Bolzano', 'Trento']},
    {regione: 'Umb', province: ['Perugia', 'Terni']},
    {regione: 'Val', province: ["Valle d'Aosta"]},
    {regione: 'Ven', province: ['Belluno', 'Padova', 'Rovigo', 'Treviso', 'Venezia', 'Verona', 'Vicenza']},
]; */